# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da648342330e912e37205876fc64ed0567ef7ec801b4f1f11f0f3a1f67fa84ee0a7073d65785cdc795d93eda451ecaf4ebb15e7cd3532f72dc07177bedcf86e

test:
  secret_key_base: 4bd185713421c3e5c245cf3163ec3938ad45bc323f23915560410cbdfe6cc5b730b2c45f225b44fd9ebc80dfa1fe2cd9e942d94b2dd949e709263a1ea607acc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
